remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: jeykll-theme-minimal
#alternative theme : https://github.com/pages-themes/cayman

title: Abhijit bhavsar
description: Abhijit is a data engineer, UI UX designer and Photographer
